name: icogen
description: A sample command-line application.
version: 1.0.0+1
homepage: https://github.com/rxlabz/icogen
author: rxlabz <rxlabz@gmail.com>

executables:
  icogen:

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  #path: ^1.4.1
  rxdart: ^0.22.0
  image: ^2.1.4
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
